import Navbar from '@/components/Navbar'
import './globals.css'
import { ErrorWrapper } from './error-wrapper'
//21 no videos

export const metadata = {
  title: {
    default: 'Next.js Tutorial',
    template: '%s | Tutorial'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className='px-10 py-20'>
          <ErrorWrapper>
            {children}
          </ErrorWrapper>
        </div>
      </body>
    </html>
  )
}
